# Diego Hernández

version: '3.8'

services:

  mongo: 
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: ElMercaderLTDA
    volumes:
      - mongo_db_data:/data/db
      - ./ElMercader_mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

    
  # api contiene todo el backend, donde nginx redirigirá al back como "api"
  api:
    build: ./ElMercader_backend
    ports:
    # El proyecto, desde el localhost está utilizando el puerto 8081
    # nginx usa el 8080
      - 8081:8080
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://root:root@mongo:27017/ElMercaderLTDA}
      - TZ=${TZ:-America/Denver}
    depends_on:
      - mongo

  # Agregar un servicio que sea dedicado al front
  view:
    build: ./ElMercader_frontend
    ports:
      - 3000:3000
    environment:
      - API_URI=${API_URI}
    depends_on:
      - api

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3306:80
    depends_on:
      - view


volumes:
  mongo_db_data:
  
